server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


# application.yml
kakao:
  api:
    clientId: 5617b43c5e1f8f47e45f4d510a88e8fc
    clientSecret: 5yc5smUCscGZlKcfjqsfV46wFiVdsbzq


# application.yml
naver:
  api:
    key: YOUR_KAKAO_REST_API_KEY