server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:templates//
    suffix: .html
    mode: HTML
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/TMRTeamProject?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # ← 요게 핵심!!
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1042006957683-qrmsmr42e04771d74v6f1sssung4aukt.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google" # ✅ 이거 있어야 함
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/user.phonenumbers.read
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo



# 카카오 api 키
kakao:
  api:
    clientId: 5617b43c5e1f8f47e45f4d510a88e8fc
    clientSecret: 5yc5smUCscGZlKcfjqsfV46wFiVdsbzq

# 네이버 api 키
naver:
  api:
    clientId: bEMZzWiWu06Pk2b7R6D3
    clientSecret: 730aCbbDQO

# SMS 문자 api 키
solapi:
  apiKey: NCS8X6JXYL5LGJ0B
  apiSecret: OPMRNQJAWXRAEDUGNAOPOI8AZNRTTSCO
  sender: 01030417745