server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:templates//
    suffix: .html
    mode: HTML
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/TMRTeamProject?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ""



# application.yml
kakao:
  api:
    clientId: 5617b43c5e1f8f47e45f4d510a88e8fc
    clientSecret: 5yc5smUCscGZlKcfjqsfV46wFiVdsbzq


# application.yml
naver:
  api:
    clientId: bEMZzWiWu06Pk2b7R6D3
    clientSecret: 730aCbbDQO

solapi:
  apiKey: NCS8X6JXYL5LGJ0B
  apiSecret: OPMRNQJAWXRAEDUGNAOPOI8AZNRTTSCO
  sender: 01030417745